name: Frontend prod-CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # ✅ 1. Checkout
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  # ✅ 2. Setup Node.js
  setup:
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: ./kakaobase
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Install Dependencies
        run: npm ci

  # ✅ 6. Build & Deploy (release/** 또는 main 브랜치에서 실행, Blue/Green)
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Determine Docker Tag
        id: tag
        run: |
            echo "DOCKER_TAG=prod" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      - name: Build and push Docker image
        working-directory: ./kakaobase
        run: |
          FRONTEND_IMAGE_BASE=${{ secrets.ECR_REGISTRY }}/${{ secrets.FRONTEND_REPO }}
          FE_IMAGE_SHA=$FRONTEND_IMAGE_BASE:${{ steps.tag.outputs.DOCKER_TAG }}-${{ github.sha }}
          FE_IMAGE_LATEST=$FRONTEND_IMAGE_BASE:latest
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.PROD_NEXT_PUBLIC_API_URL }} \
            --build-arg NEXT_PUBLIC_GOOGLE_ANALYTICS=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }} \
            -t $FE_IMAGE_SHA -t $FE_IMAGE_LATEST .
          docker push $FE_IMAGE_SHA
          docker push $FE_IMAGE_LATEST
          echo "{\"frontendImage\":\"$FE_IMAGE_SHA\", \"ecrRepo\":\"$FRONTEND_IMAGE_BASE\", \"awsRegion\":\"${{ secrets.AWS_REGION }}\", \"prodApiUrl\":\"${{ secrets.PROD_NEXT_PUBLIC_API_URL }}\", \"googleAnalytics\":\"${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}\"}" > imageDetail.json

      - name: Prepare deploy bundle
        working-directory: ./kakaobase
        run: |
          mkdir -p bundle/scripts
          cp appspec.yml imageDetail.json bundle/
          cp -r scripts/* bundle/scripts/
          cd bundle && zip -r ../fe-deploy.zip . && cd ..

      - name: Upload to S3
        run: |
          aws s3 cp ./kakaobase/fe-deploy.zip s3://${{ secrets.S3_BUCKET }}/fe/fe-deploy.zip

      - name: Determine Deployment Target
        id: target
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "APP_NAME=BlueGreen-FE" >> "$GITHUB_OUTPUT"
            echo "DEPLOY_GROUP=BlueGreen-FE-Group" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" =~ ^refs/heads/release/ ]]; then
            echo "APP_NAME=frontend-release" >> "$GITHUB_OUTPUT"
            echo "DEPLOY_GROUP=frontend-release-group" >> "$GITHUB_OUTPUT"
          else
            echo "No deployment target for this branch." >&2
            exit 1
          fi

      - name: Trigger CodeDeploy Deployment (Blue/Green)
        run: |
          aws deploy create-deployment \
            --application-name ${{ steps.target.outputs.APP_NAME }} \
            --deployment-group-name ${{ steps.target.outputs.DEPLOY_GROUP }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=fe/fe-deploy.zip,bundleType=zip \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  # ✅ 7. Discord Notification on Failure
  notify:
    name: Discord Notification
    needs: build
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        run: |
          if [ "${{ needs.build.result }}" == "success" ]; then
            STATUS="✅ Next.js 배포 성공"
            COLOR="5763719"
          else
            STATUS="❌ Next.js 배포 실패"
            COLOR="15158332"
          fi
          
          curl -X POST -H "Content-Type: application/json" \
            -d "{
              \"embeds\": [{
                \"title\": \"$STATUS: ${{ github.workflow }}\",
                \"description\": \"브랜치: \`${{ github.ref_name }}\`\n커밋한 사람: \`${{ github.actor }}\`\n[👉 액션 보기](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\",
                \"color\": $COLOR
              }]
            }" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}